import ast
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"
BUILD_DIR = PROJECT_ROOT / "build"
DEPS_FILE = BUILD_DIR / "deps.mk"


def build_import_graph() -> dict[Path, set[Path]]:
    graph = {}
    for py_path in SRC_DIR.glob("**/*.py"):
        if py_path.name.startswith("__"):
            continue
        try:
            content = py_path.read_text()
            tree = ast.parse(content, filename=str(py_path))
        except Exception:
            continue

        imported_paths = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    parts = alias.name.split(".")
                    target = SRC_DIR.joinpath(*parts).with_suffix(".py")
                    if target.exists():
                        imported_paths.add(target)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    parts = node.module.split(".")
                    target = SRC_DIR.joinpath(*parts).with_suffix(".py")
                    if target.exists():
                        imported_paths.add(target)
                    target_dir_file = SRC_DIR.joinpath(*parts)
                    for alias in node.names:
                        sub_file = target_dir_file.joinpath(f"{alias.name}.py")
                        if sub_file.exists():
                            imported_paths.add(sub_file)

        graph[py_path] = imported_paths
    return graph


def discover_python_deps_fast(
    py_path: Path, graph: dict[Path, set[Path]]
) -> set[str]:
    visited = set()
    queue = [py_path]
    deps = set()

    while queue:
        curr = queue.pop()
        if curr in visited:
            continue
        visited.add(curr)

        if curr != py_path:
            rel = str(curr.resolve().relative_to(PROJECT_ROOT))
            deps.add(rel)

        for neighbor in graph.get(curr, []):
            if neighbor not in visited:
                queue.append(neighbor)

    return deps


def discover_stl_deps_fast(py_path: Path) -> set[str]:
    stls = set()
    try:
        content = py_path.read_text()
        matches = re.findall(r"build/[a-zA-Z0-9_/-]+\.(?:stl|3mf)", content)
        stls.update(matches)

        if "female_pin_header_wire_holes_" in content:
            for n in range(2, 10):
                stls.add(
                    f"build/components/female_pin_header/cad/female_pin_header_wire_holes_{n}.stl"
                )
    except Exception:
        pass
    return stls


def generate_deps():
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    graph = build_import_graph()

    rules = []
    rules.append(
        "# Automatically generated by scripts/scan_deps.py — DO NOT EDIT\n"
    )

    for py_path in sorted(SRC_DIR.glob("**/*.py")):
        if py_path.name.startswith("__"):
            continue

        rel_from_src = py_path.relative_to(SRC_DIR)
        rel_py_str = f"src/{rel_from_src}"

        target_stl = f"build/{rel_from_src.with_suffix('.stl')}"
        target_3mf = f"build/{rel_from_src.with_suffix('.3mf')}"

        py_deps = discover_python_deps_fast(py_path, graph)
        py_deps.add(rel_py_str)
        stl_deps = discover_stl_deps_fast(py_path)

        all_deps = sorted(py_deps) + sorted(stl_deps)
        deps_str = " ".join(all_deps)

        rules.append(f"{target_stl}: {deps_str}")
        rules.append(f"{target_3mf}: {deps_str}")

    DEPS_FILE.write_text("\n".join(rules) + "\n")
    print(f"DEPS\t{DEPS_FILE.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    generate_deps()
